dropdown_options = {
    "incident_rate": "Incident Rate",
    "fatality_rate": "Fatality Rate",
    "lost_workday_rate": "Lost Workday Rate per Injury",
    "severity_index": "Severity Index",
    "death_to_incident": "Death-to-Incident Ratio",
    "safety_score": "Aggregated Safety Score",
}

dropdown_options_rev = {
    "Incident Rate": "incident_rate",
    "Fatality Rate": "fatality_rate",
    "Lost Workday Rate": "lost_workday_rate",
    "Severity Index": "severity_index",
    "Death To Incident": "death_to_incident",
    "Safety Score": "safety_score",
}

state_map = {
    "AK": "Alaska",
    "AL": "Alabama",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DC": "District of Columbia",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "PR": "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming",
}

state_code_map = {value: index+1 for index, value in enumerate(dict(sorted(state_map.items(), reverse=True)).keys())}

reverse_dropdown_options = {v: k for k, v in dropdown_options.items()}
